kind: PersistentVolume
apiVersion: v1
metadata:
  name: efk-volume
  labels:
    type: local
spec:
  storageClassName: data-elasticsearch-data-0
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/efk-data"
  