apiVersion: v1
kind: Service
metadata:
  name: nginx-two
  labels:
    app: nginx-two
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: nginx-pod-port
    nodePort: 31111
    protocol: TCP
    name: web
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx-two
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx-two
    spec:
      containers:
      - name: nginx-two
        image: nginx:1.15.1
        ports:
        - containerPort: 80
          name: nginx-pod-port
