kind: PersistentVolume
apiVersion: v1
metadata:
  name: rabbitmq-data-volume
  labels:
    type: local
spec:
  storageClassName: rabbitmq-storage
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/rabbitmq"
