# To install:
# helm install stable/rabbitmq-ha --name my-rabbit --namespace rabbit -f rabbit-values.yaml

replicas: 3

service:
  type: NodePort 

rabbitmqUsername: guest
rabbitmqPassword: guest
rabbitmqNodePort: 31000
