# To install:
# helm install stable/rabbitmq-ha --name my-rabbit --namespace rabbit -f rabbit-values.yam

service:
  clusterIP:
  type: NodePort

rabbitmqNodePort: 31000
rabbitmqManagerPort: 31001
rabbitmqUser: guest
rabbitmqPassword: guest
