# To install:
# helm install stable/rabbitmq --name my-rabbit --namespace rabbit -f rabbit-values.yam

replicas: 3

rbacEnabled: false

service:
  type: NodePort 
  nodePort: 31333

rabbitmq:
  username: admin
  password: admin
