kind: PersistentVolume
apiVersion: v1
metadata:
  name: sonarqube-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/bitnami/rabbitmq/var/lib/rabbitmq"
  