image:
  tag: 7.7-community

service:
  type: NodePort
  # Chart does not allow setting of actual nodePort number, so a
  # patch after installation is applied. 
  # (https://github.com/helm/charts/blob/master/stable/sonarqube/templates/service.yaml)

persistence:
  storageClass: manual
  enabled: false
  size: 10Gi
  accessMode: ReadWriteOnce

postgresql:
  persistence:
    size: 10Gi
    storageClass: manual

sonarProperties:
  sonar.forceAuthentication=false

plugins:
  install:
    - 'https://github.com/SonarQubeCommunity/sonar-pmd/releases/download/3.2.0/sonar-pmd-plugin-3.2.0.jar'
    - 'https://github.com/spotbugs/sonar-findbugs/releases/download/3.11.0/sonar-findbugs-plugin-3.11.0.jar'
    - 'https://github.com/checkstyle/sonar-checkstyle/releases/download/4.20/checkstyle-sonar-plugin-4.20.jar'
