service:
  type: NodePort

#plugins:
# install
# TODO - These plugins are causing SonarQube failures
#  - 'https://github.com/SonarQubeCommunity/sonar-pmd/releases/download/2.6/sonar-pmd-plugin-2.6.jar'
#  - 'https://github.com/spotbugs/sonar-findbugs/releases/download/3.6.0/sonar-findbugs-plugin-3.6.0.jar'
#  - 'https://github.com/checkstyle/sonar-checkstyle/releases/download/4.11/checkstyle-sonar-plugin-4.11.jar'
# to bump these plugin versions higher some require a newer version of SonarQube,
# but newer versions of SonarQube fail to start (see at top).

# When running SonarQube in a limited cluster, such as on Katacoda SonarQube may fail and 
# log "Process exited with exit value [es]: 137". This error happens when SonarQube does
# not have enough memory. SonarQube relies on ElasticSearch which by itself is memory
# intensive. There are some properties to reduce memory consumption in this case:
#
# For Web: sonar.web.javaOpts
# For ElasticSearch: sonar.search.javaOpts
# For Compute Engine: sonar.ce.javaOpts
# https://github.com/10up/wp-local-docker/issues/6

sonarProperties:
  sonar.forceAuthentication=false
  # sonar.search.javaOpts=-Xms512m -Xmx512m -XX:+HeapDumpOnOutOfMemoryError

persistence:
  storageClass: manual