image:
  tag: 7.7-community

service:
  type: NodePort
  # Chart does not allow setting of actual nodePort number, so a
  # patch after installation is applied. 
  # (https://github.com/helm/charts/blob/master/stable/sonarqube/templates/service.yaml)

persistence:
  storageClass: manual
  enabled: false
  size: 10Gi
  accessMode: ReadWriteOnce

postgresql:
  persistence:
    size: 10Gi
    storageClass: manual

sonarProperties:
  sonar.forceAuthentication=false

#plugins:
# install
# TODO - These plugins were causing SonarQube failures, plan to test with latest version
#  - 'https://github.com/SonarQubeCommunity/sonar-pmd/releases/download/2.6/sonar-pmd-plugin-2.6.jar'
#  - 'https://github.com/spotbugs/sonar-findbugs/releases/download/3.6.0/sonar-findbugs-plugin-3.6.0.jar'
#  - 'https://github.com/checkstyle/sonar-checkstyle/releases/download/4.11/checkstyle-sonar-plugin-4.11.jar'
# to bump these plugin versions higher some require a newer version of SonarQube.
